spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sbb?serverTimezone=UTC
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace